// utils/languageMap.ts
export const languageMap: { [key: string]: string } = {
        en: "English",
        de: "German",
        es: "Spanish",
        fr: "French",
        pt: "Portuguese",
        ru: "Russian",
        tr: "Turkish",
        nl: "Dutch",
        it: "Italian",
        sv: "Swedish",
        pl: "Polish",
        cs: "Czech",
        da: "Danish",
        fi: "Finnish",
        hu: "Hungarian",
        no: "Norwegian",
        el: "Greek",
        ro: "Romanian",
        bg: "Bulgarian",
        uk: "Ukrainian",
        sk: "Slovak",
        hr: "Croatian",
        sr: "Serbian",
        he: "Hebrew",
        ar: "Arabic",
        fa: "Persian",
        hi: "Hindi",
        bn: "Bengali",
        zh: "Chinese",
        ja: "Japanese",
        ko: "Korean",
        th: "Thai",
        vi: "Vietnamese",
        id: "Indonesian",
        ms: "Malay",
        tl: "Tagalog",
        sw: "Swahili"

    
  };